# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHMDoCyQFJC_vYtyJ_NhISGtOb1fgK2G
"""

def convert_currency(amount, exchange_rate):
    converted_amount = amount * exchange_rate
    return converted_amount

print("Currency Converter")

while True:
    print("\nPlease select conversion direction:")
    print("1. USD to EUR")
    print("2. EUR to USD")
    print("3. Quit")

    choice = input("Enter choice (1-3): ")

    if choice == '3':
        break

    if choice in ('1', '2'):
        amount = float(input("Enter amount to convert: "))
        if choice == '1':
            exchange_rate = 0.82  # exchange rate USD to EUR
            converted_amount = convert_currency(amount, exchange_rate)
            print("$", amount, "is equivalent to €", round(converted_amount, 2))
        else:
            exchange_rate = 1.22  # exchange rate EUR to USD
            converted_amount = convert_currency(amount, exchange_rate)
            print("€", amount, "is equivalent to $", round(converted_amount, 2))

    else:
        print("Invalid input")